/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Estable */

#ifndef _Included_Estable
#define _Included_Estable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Estable
 * Method:    SCardEstablishContext
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_Estable_SCardEstablishContext
  (JNIEnv *, jclass, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
